== Deployment

=== Pre-requisites

* Base infrastructure setup
** Tools and utilities to be installed locally
https://docs.inji.io/readme/setup/deploy#tools-and-utilities[steps]
** System Requirements: Hardware, network and certificate requirements
https://docs.inji.io/readme/setup/deploy#system-requirements[steps]
** Set up Wireguard Bastion Host
https://docs.inji.io/readme/setup/deploy#wireguard[steps]
** K8s Cluster setup
https://docs.inji.io/readme/setup/deploy#k8-cluster-setup[steps]
** NGINX setup and configuration
https://docs.inji.io/readme/setup/deploy#nginx-for-inji-k8-cluster[steps]
** K8s Cluster Configuration
https://docs.inji.io/readme/setup/deploy#k8-cluster-configuration[steps]
* inji-stack-config ConfigMap
https://docs.inji.io/readme/setup/deploy#pre-requisites[steps]
* Postgres installation
https://github.com/mosip/mosip-infra/tree/v1.2.0.2/deployment/v3/external/postgres[steps]
** Note: Before running the Postgres install script, update the
`POSTGRES++_++HOST` value in `install.sh` with the correct PostgreSQL
host.
* Config server secerts
https://github.com/mosip/mosip-infra/tree/v1.2.0.2/deployment/v3/mosip/conf-secrets[steps]
* Config server installation
https://docs.inji.io/readme/setup/deploy#config-server-installation[steps]
* Artifactory installation
https://github.com/mosip/artifactory-ref-impl/tree/v1.3.0-beta.2/deploy[steps]
* redis installation

....
cd deploy/redis
./install.sh
....

=== Initialise pre-requisites

==== link:../db_scripts[DB init]

* Update values file for postgres init
link:../db_scripts/init_values.yaml[here].
+
....
 cd ../../db_scripts
./init_db.sh
....
+
=== Install inji certify
+
....
 cd ../inji-certify
  ./install.sh
....
+
=== link:inji-certify-apitestrig[inji certify apitestrig]
